package org.revature.domain;

import org.revature.TransactionType;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class Transaction {
    private long accountNumber;
    private TransactionType type;
    private BigDecimal amount;
    private Long relatedAccount;

    // These two are generated by Postgres
    private Timestamp timestamp;
    private Long id;

    public Transaction(long accountNumber, TransactionType type, BigDecimal amount, Long relatedAccount, Timestamp timestamp, Long id) {
        this.accountNumber = accountNumber;
        this.type = type;
        this.amount = amount;
        this.relatedAccount = relatedAccount;
        this.timestamp = timestamp;
        this.id = id;
    }

    public Transaction(long accountNumber, TransactionType type, BigDecimal amount, Long relatedAccount) {
        this.accountNumber = accountNumber;
        this.type = type;
        this.amount = amount;
        this.relatedAccount = relatedAccount;
    }

    public Transaction(long accountNumber, TransactionType type, BigDecimal amount) {
        this.accountNumber = accountNumber;
        this.type = type;
        this.amount = amount;
    }

    // Getters and setters
    public long getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(long accountNumber) {
        this.accountNumber = accountNumber;
    }

    public TransactionType getType() {
        return type;
    }

    public void setType(TransactionType type) {
        this.type = type;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Long getRelatedAccount() {
        return relatedAccount;
    }

    public void setRelatedAccount(Long relatedAccount) {
        this.relatedAccount = relatedAccount;
    }

    public Timestamp getTimestamp() {
        return timestamp;
    }

    public Long getId() {
        return id;
    }
}
